// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: proto/service-1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequestParam_Type int32

const (
	SearchRequestParam_PC     SearchRequestParam_Type = 0
	SearchRequestParam_Mobile SearchRequestParam_Type = 1
)

// Enum value maps for SearchRequestParam_Type.
var (
	SearchRequestParam_Type_name = map[int32]string{
		0: "PC",
		1: "Mobile",
	}
	SearchRequestParam_Type_value = map[string]int32{
		"PC":     0,
		"Mobile": 1,
	}
)

func (x SearchRequestParam_Type) Enum() *SearchRequestParam_Type {
	p := new(SearchRequestParam_Type)
	*p = x
	return p
}

func (x SearchRequestParam_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchRequestParam_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_service_1_proto_enumTypes[0].Descriptor()
}

func (SearchRequestParam_Type) Type() protoreflect.EnumType {
	return &file_proto_service_1_proto_enumTypes[0]
}

func (x SearchRequestParam_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchRequestParam_Type.Descriptor instead.
func (SearchRequestParam_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_service_1_proto_rawDescGZIP(), []int{0, 0}
}

type SearchRequestParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryText string                  `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`    // 字符串类型 | 后面的「1」为数字标识符，在消息定义中需要唯一
	Limit     int32                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                            // 整型
	Type      SearchRequestParam_Type `protobuf:"varint,4,opt,name=type,proto3,enum=SearchRequestParam_Type" json:"type,omitempty"` // 枚举类型
}

func (x *SearchRequestParam) Reset() {
	*x = SearchRequestParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequestParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequestParam) ProtoMessage() {}

func (x *SearchRequestParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequestParam.ProtoReflect.Descriptor instead.
func (*SearchRequestParam) Descriptor() ([]byte, []int) {
	return file_proto_service_1_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequestParam) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SearchRequestParam) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequestParam) GetType() SearchRequestParam_Type {
	if x != nil {
		return x.Type
	}
	return SearchRequestParam_PC
}

type SearchResultPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     []string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"` // 「repeated」表示字段可以重复任意多次（包括0次）
	NumResults int32    `protobuf:"varint,2,opt,name=num_results,json=numResults,proto3" json:"num_results,omitempty"`
}

func (x *SearchResultPage) Reset() {
	*x = SearchResultPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_service_1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResultPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultPage) ProtoMessage() {}

func (x *SearchResultPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultPage.ProtoReflect.Descriptor instead.
func (*SearchResultPage) Descriptor() ([]byte, []int) {
	return file_proto_service_1_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResultPage) GetResult() []string {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SearchResultPage) GetNumResults() int32 {
	if x != nil {
		return x.NumResults
	}
	return 0
}

var File_proto_service_1_proto protoreflect.FileDescriptor

var file_proto_service_1_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d,
	0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x50, 0x43, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x10, 0x01, 0x22, 0x4b, 0x0a,
	0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d,
	0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_service_1_proto_rawDescOnce sync.Once
	file_proto_service_1_proto_rawDescData = file_proto_service_1_proto_rawDesc
)

func file_proto_service_1_proto_rawDescGZIP() []byte {
	file_proto_service_1_proto_rawDescOnce.Do(func() {
		file_proto_service_1_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service_1_proto_rawDescData)
	})
	return file_proto_service_1_proto_rawDescData
}

var file_proto_service_1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_service_1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_service_1_proto_goTypes = []interface{}{
	(SearchRequestParam_Type)(0), // 0: SearchRequestParam.Type
	(*SearchRequestParam)(nil),   // 1: SearchRequestParam
	(*SearchResultPage)(nil),     // 2: SearchResultPage
}
var file_proto_service_1_proto_depIdxs = []int32{
	0, // 0: SearchRequestParam.type:type_name -> SearchRequestParam.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_service_1_proto_init() }
func file_proto_service_1_proto_init() {
	if File_proto_service_1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_service_1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequestParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_service_1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResultPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service_1_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_service_1_proto_goTypes,
		DependencyIndexes: file_proto_service_1_proto_depIdxs,
		EnumInfos:         file_proto_service_1_proto_enumTypes,
		MessageInfos:      file_proto_service_1_proto_msgTypes,
	}.Build()
	File_proto_service_1_proto = out.File
	file_proto_service_1_proto_rawDesc = nil
	file_proto_service_1_proto_goTypes = nil
	file_proto_service_1_proto_depIdxs = nil
}
